#include "Polynomial.cpp"

int main(){
	Polynomial a,b;
	a.set(6,1);
	a.set(3,1);
	a.set(2,1);
	a.set(1,1);
	a.set(0,1);
	std::cout << "Empty vs Non-Empty Equation Print:\n";
	std::cout << a.toString() << std::endl;
	std::cout << b.toString() << std::endl;
	std::cout << "Test Regular Equals:\n"; 
	b = a;
	std::cout << a.toString() << std::endl; 
	std::cout << b.toString() << std::endl;
	std::cout << "Add 3 seperate polynomials using +:\n";
	Polynomial t2_1,t2_2,t2_3,t2_4;
	t2_1.set(0,1);
	t2_2.set(3,2);
	t2_3.set(3,1);
	t2_4 = t2_1 + t2_2 + t2_3;
	std::cout << t2_4.toString() << std::endl;
	std::cout << "Add using +=:\n";
	Polynomial t3_1,t3_2,t3_3;
	t3_1.set(0,1);
	t3_2.set(3,2);
	t3_3.set(3,1);
	t3_3 += t3_2 += t3_1;
	std::cout <<"Before\n";
	std::cout << t3_1.toString() << std::endl;
	std::cout << t3_2.toString() << std::endl;
	std::cout << t3_3.toString() << std::endl;
	t3_3 += t3_2 += t3_1;
	std::cout <<"After\n";
	std::cout << t3_3.toString() << std::endl;
	std::cout << "Subtract 3 seperate polynomials using -:\n";
	Polynomial t4_1,t4_2,t4_3,t4_4;
	t4_1.set(0,1);
	t4_2.set(3,2);
	t4_3.set(3,1);
	t4_4 = t4_1 + t4_2 + t4_3;
	std::cout << t2_4.toString() << std::endl;
	std::cout << "Subtract using -=:\n";
	Polynomial t5_1,t5_2,t5_3;
	t5_1.set(0,1);
	t5_2.set(3,2);
	t5_3.set(3,1);
	t5_3 += t5_2 += t5_1;
	std::cout <<"Before\n";
	std::cout << t5_1.toString() << std::endl;
	std::cout << t5_2.toString() << std::endl;
	std::cout << t5_3.toString() << std::endl;
	t5_3 += t5_2 += t5_1;
	std::cout <<"After\n";
	std::cout << t5_3.toString() << std::endl;
	std::cout << "Multiply 2 polynomials with *\n";
	Polynomial x,y,z;
	x.set(1,3);
	y.set(1,2);
	y.set(2,2);
	z = x * y;
	std::cout << z.toString() << std::endl;
	std::cout << "Multiply 2 polynomials with *=\n";
	Polynomial c,d;
	c.set(1,3);
	d.set(1,2);
	d.set(2,2);
	c *= d;
	std::cout << c.toString() << std::endl;
	return 0;
} 
